//! A GMSK transmitter, for tests and for the engine's own integration test.
//!
//! sdroxide does not transmit AIS and will not: the service is
//! safety-of-life, and an amateur putting false vessel traffic on it would be
//! doing something with consequences a licence does not cover. What this module
//! is for is proving the receiver — an AIS decoder written from a standard
//! rather than from a recording has no other way to be checked at all.
//!
//! # It is built from the standard, not from the decoder
//!
//! That is the whole point, and it is a rule this module keeps deliberately:
//! the modulator here computes the Gaussian frequency pulse from `BT = 0.4` and
//! a modulation index of one half, integrates it into a phase, and stuffs and
//! NRZI-encodes the packet by the rules in ITU-R M.1371 §3.3 — none of it by
//! calling into [`crate::demod`] or [`crate::hdlc`] and running anything
//! backwards. The one thing shared with the receiver is the frame check
//! sequence, which comes from [`sdroxide_ax25::fcs`] and is itself tested
//! against catalogue values there.
//!
//! A self-consistent test signal — one generated by inverting the decoder — is
//! worth nothing: it agrees with whatever the decoder happens to do, including
//! the parts that are wrong.
//!
//! # What it still cannot prove
//!
//! That the *standard* was read correctly. If a field offset here and the one
//! in [`crate::message`] are wrong in the same way, both agree and neither is
//! right. The panel's `!AIVDM` readout is the answer to that: a sentence an
//! operator can paste into any other AIS tool and compare.
//!
//! # The ambiguity worth naming
//!
//! The standard describes the training sequence as "24 bits alternating 0 and
//! 1" and, separately, says the packet is NRZI-encoded. Whether the alternation
//! is the bit stream before that encoding (which puts a 2400 Hz tone on the
//! air) or the line after it (4800 Hz) is not stated in so many words. This
//! transmitter NRZI-encodes the whole packet, training included. Nothing in the
//! receiver depends on which is right: the frame is found by hunting for a
//! flag, and the bit timing is measured over the data rather than acquired from
//! the preamble.

use std::f64::consts::TAU;

use sdroxide_dsp::Complex32;
use sdroxide_types::AIS_BIT_RATE;

use crate::hdlc::{FLAG, bits_lsb_first, octets_lsb_first};

/// How the test transmitter is set up.
#[derive(Debug, Clone, Copy)]
pub struct TxParams {
    pub sample_rate: f64,
    /// Bandwidth-time product of the Gaussian pre-filter.
    pub bt: f64,
    /// Peak deviation, Hz. A modulation index of one half at 9600 bit/s.
    pub deviation_hz: f64,
    /// Bits the amplitude ramp rises over, at each end.
    pub ramp_bits: usize,
    /// Peak envelope amplitude.
    pub amplitude: f32,
}

impl Default for TxParams {
    fn default() -> Self {
        TxParams {
            sample_rate: 75_000.0,
            bt: 0.4,
            deviation_hz: AIS_BIT_RATE / 4.0,
            ramp_bits: 8,
            amplitude: 0.5,
        }
    }
}

/// Bits of quiet lead-in before the first line bit's centre, so the frequency
/// pulse's own tail is inside the burst.
const LEAD_BITS: f64 = 2.0;

impl TxParams {
    pub fn sps(&self) -> f64 {
        self.sample_rate / AIS_BIT_RATE
    }

    /// Where the first line bit's centre lands in the produced samples.
    ///
    /// Exported because it is the only fixed point a timing test can measure
    /// against — see [`crate::demod`]'s.
    pub fn first_bit_center_sample(&self) -> f64 {
        LEAD_BITS * self.sps()
    }
}

/// The Gaussian frequency pulse: a bit-wide rectangle smoothed by a Gaussian
/// of bandwidth `bt` times the bit rate, in units where `u` is bits.
///
/// Unit area, so a long run of the same bit reaches exactly the peak deviation
/// — which is what makes a modulation index of one half mean what it says.
fn pulse(u: f64, bt: f64) -> f64 {
    // The Gaussian's standard deviation in bit periods, from its bandwidth:
    // `σ = √(ln 2) / (2π·B·T)`.
    let sigma = (2f64.ln()).sqrt() / (TAU * bt);
    phi((u + 0.5) / sigma) - phi((u - 0.5) / sigma)
}

/// The standard normal distribution function.
fn phi(z: f64) -> f64 {
    0.5 * (1.0 + erf(z / 2f64.sqrt()))
}

/// Abramowitz & Stegun 7.1.26 — good to 1.5e-7, which is far below anything a
/// float sample carries.
fn erf(x: f64) -> f64 {
    const P: f64 = 0.327_591_1;
    const A: [f64; 5] =
        [0.254_829_592, -0.284_496_736, 1.421_413_741, -1.453_152_027, 1.061_405_429];
    let sign = if x < 0.0 { -1.0 } else { 1.0 };
    let x = x.abs();
    let t = 1.0 / (1.0 + P * x);
    let poly = A.iter().rev().fold(0.0, |acc, &a| (acc + a) * t);
    sign * (1.0 - poly * (-x * x).exp())
}

/// The complete line of a transmission: training, flags, stuffed body, NRZI.
fn line_levels(data_bits: &[bool]) -> Vec<bool> {
    let mut bits: Vec<bool> = Vec::new();
    // The training sequence: 24 alternating bits.
    for k in 0..24 {
        bits.push(k % 2 == 1);
    }
    let flag: Vec<bool> = (0..8).map(|i| FLAG >> i & 1 != 0).collect();
    bits.extend_from_slice(&flag);

    // Body: the data field and the check sequence over it.
    let mut body = data_bits.to_vec();
    let fcs = sdroxide_ax25::fcs::fcs(&octets_lsb_first(&body));
    body.extend(bits_lsb_first(&fcs));

    // ...stuffed: a zero after every five ones, so `0111_1110` can only ever be
    // a flag.
    let mut ones = 0;
    for &b in &body {
        bits.push(b);
        if b {
            ones += 1;
            if ones == 5 {
                bits.push(false);
                ones = 0;
            }
        } else {
            ones = 0;
        }
    }
    bits.extend_from_slice(&flag);

    // NRZI over the whole packet: a zero is a change of level.
    let mut level = false;
    let mut line = Vec::with_capacity(bits.len() + 1);
    line.push(level);
    for &b in &bits {
        if !b {
            level = !level;
        }
        line.push(level);
    }
    line
}

/// Modulate a data field given as octets — the form a frame arrives in.
pub fn modulate(data: &[u8], p: &TxParams) -> Vec<Complex32> {
    modulate_bits(&bits_lsb_first(data), p)
}

/// Modulate a data field given as the bit stream itself, most significant bit
/// of the message first — the form [`crate::message`] reads.
pub fn modulate_bits(data_bits: &[bool], p: &TxParams) -> Vec<Complex32> {
    let line = line_levels(data_bits);
    let sps = p.sps();
    let n = ((line.len() as f64 + 2.0 * LEAD_BITS) * sps).ceil() as usize;

    // The frequency pulse spans four bits either side, which is far past where
    // a Gaussian of this width has anything left.
    let span = (4.0 * sps).ceil() as isize;
    let mut out = Vec::with_capacity(n);
    let mut phase = 0f64;
    for i in 0..n {
        // Where this sample sits, in bits from the first bit's centre.
        let u = i as f64 / sps - LEAD_BITS;
        let k0 = u.round() as isize;
        let mut sum = 0f64;
        for k in (k0 - span / sps as isize - 2)..=(k0 + span / sps as isize + 2) {
            let Ok(idx) = usize::try_from(k) else { continue };
            let Some(&lvl) = line.get(idx) else { continue };
            let a = if lvl { 1.0 } else { -1.0 };
            sum += a * pulse(u - k as f64, p.bt);
        }
        phase += TAU * p.deviation_hz * sum / p.sample_rate;
        let env = envelope(i as f64 / sps, line.len() as f64, p.ramp_bits as f64);
        out.push(Complex32::new(
            (p.amplitude as f64 * env * phase.cos()) as f32,
            (p.amplitude as f64 * env * phase.sin()) as f32,
        ));
    }
    out
}

/// The transmitter's amplitude ramp: up over the first bits of the training
/// sequence, down again after the closing flag.
fn envelope(u: f64, bits: f64, ramp: f64) -> f64 {
    let rise = ((u / ramp).clamp(0.0, 1.0) * std::f64::consts::PI / 2.0).sin();
    let end = bits + LEAD_BITS;
    let fall = (((end - u) / ramp).clamp(0.0, 1.0) * std::f64::consts::PI / 2.0).sin();
    rise * fall
}

/// Move a complex signal by `hz` — a receiver whose clock is out, as far as
/// anything downstream can tell.
pub fn shift(iq: &mut [Complex32], hz: f64, rate: f64) {
    for (i, z) in iq.iter_mut().enumerate() {
        let th = TAU * hz * i as f64 / rate;
        *z *= Complex32::new(th.cos() as f32, th.sin() as f32);
    }
}

/// A small deterministic noise source. Its own rather than a dependency so a
/// test that fails fails the same way on every machine.
pub struct Noise {
    state: u64,
    spare: Option<f32>,
}

impl Noise {
    pub fn new(seed: u64) -> Noise {
        Noise { state: seed | 1, spare: None }
    }

    fn next_u64(&mut self) -> u64 {
        // xorshift64*: short, and good enough for a noise floor.
        let mut x = self.state;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.state = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }

    fn uniform(&mut self) -> f64 {
        (self.next_u64() >> 11) as f64 / (1u64 << 53) as f64
    }

    /// One normal sample of standard deviation `sigma`, per component.
    pub fn gaussian(&mut self, sigma: f32) -> Complex32 {
        if let Some(im) = self.spare.take() {
            return Complex32::new(im * sigma, self.normal() * sigma);
        }
        let (a, b) = self.box_muller();
        self.spare = None;
        Complex32::new(a * sigma, b * sigma)
    }

    fn normal(&mut self) -> f32 {
        self.box_muller().0
    }

    fn box_muller(&mut self) -> (f32, f32) {
        let u1 = self.uniform().max(1e-12);
        let u2 = self.uniform();
        let r = (-2.0 * u1.ln()).sqrt();
        ((r * (TAU * u2).cos()) as f32, (r * (TAU * u2).sin()) as f32)
    }

    /// Add noise of standard deviation `sigma` per component to a signal.
    pub fn add(&mut self, iq: &mut [Complex32], sigma: f32) {
        for z in iq.iter_mut() {
            *z += self.gaussian(sigma);
        }
    }
}

/// A bit-field builder for a message payload: the standard's tables, written
/// out as offsets and widths.
///
/// Most significant bit first, which is the order [`crate::message`] reads and
/// *not* the order the check sequence is computed in — see [`crate::hdlc`].
#[derive(Debug, Clone)]
pub struct Payload {
    bits: Vec<bool>,
}

impl Payload {
    pub fn new(len: usize) -> Payload {
        Payload { bits: vec![false; len] }
    }

    #[must_use]
    pub fn put(mut self, at: usize, n: usize, value: u64) -> Payload {
        for k in 0..n {
            if let Some(b) = self.bits.get_mut(at + k) {
                *b = value >> (n - 1 - k) & 1 != 0;
            }
        }
        self
    }

    #[must_use]
    pub fn put_signed(self, at: usize, n: usize, value: i64) -> Payload {
        let mask = if n >= 64 { u64::MAX } else { (1u64 << n) - 1 };
        self.put(at, n, (value as u64) & mask)
    }

    /// `n` six-bit characters, padded with `@` the way a transmitter pads a
    /// fixed-width field.
    #[must_use]
    pub fn put_text(mut self, at: usize, n: usize, s: &str) -> Payload {
        let up = s.to_ascii_uppercase();
        let mut chars = up.chars();
        for k in 0..n {
            let v = match chars.next() {
                Some(c) => sixbit_value(c),
                None => 0,
            };
            self = self.put(at + k * 6, 6, u64::from(v));
        }
        self
    }

    pub fn bits(&self) -> Vec<bool> {
        self.bits.clone()
    }
}

/// A character's place in the payload alphabet, or `@` for anything not in it.
fn sixbit_value(c: char) -> u8 {
    let c = c as u32;
    match c {
        64..=95 => (c - 64) as u8, // '@'..'_'
        32..=63 => c as u8,        // ' '..'?'
        _ => 0,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The modulator produces the deviation a modulation index of one half
    /// asks for: a long run of one level sits at ±2400 Hz, and the transition
    /// between two costs exactly a quarter turn of phase.
    ///
    /// Measured off the produced samples rather than off the formula, because
    /// what the rest of this crate is tested against is the samples.
    #[test]
    fn the_deviation_is_what_a_modulation_index_of_one_half_asks_for() {
        let p = TxParams { sample_rate: 96_000.0, ramp_bits: 0, ..TxParams::default() };
        // A data field of all zeros gives a line that toggles every bit; all
        // ones gives one that holds. The held one is where the deviation is.
        let iq = modulate_bits(&[true; 40], &p);
        let sps = p.sps();
        // Well inside the frame, past the training and the opening flag.
        let mid = (60.0 * sps) as usize;
        let d = iq[mid + 1] * iq[mid].conj();
        let hz = d.im.atan2(d.re) as f64 / TAU * p.sample_rate;
        assert!(
            (hz.abs() - 2_400.0).abs() < 120.0,
            "a held level should sit at the full deviation, not {hz} Hz"
        );
    }

    /// The frequency pulse has unit area, which is the property that makes the
    /// deviation come out right, and it is symmetric about the bit centre.
    #[test]
    fn the_frequency_pulse_has_unit_area() {
        let step = 0.001;
        let area: f64 = (-4000..=4000).map(|i| pulse(i as f64 * step, 0.4) * step).sum();
        assert!((area - 1.0).abs() < 1e-6, "area {area}");
        assert!((pulse(0.3, 0.4) - pulse(-0.3, 0.4)).abs() < 1e-12);
        // A Gaussian of BT 0.4 spreads a bit over about two: the pulse still
        // has real amplitude one whole bit away, which is what makes this GMSK
        // rather than MSK.
        assert!(pulse(1.0, 0.4) > 0.03, "{}", pulse(1.0, 0.4));
        assert!(pulse(2.0, 0.4) < 0.001, "{}", pulse(2.0, 0.4));
    }

    /// The error function approximation is the one it claims to be.
    #[test]
    fn the_error_function_matches_its_published_values() {
        for (x, want) in [(0.0, 0.0), (0.5, 0.5204999), (1.0, 0.8427008), (2.0, 0.9953223)] {
            assert!((erf(x) - want).abs() < 2e-7, "erf({x}) = {}", erf(x));
            assert!((erf(-x) + want).abs() < 2e-7);
        }
    }

    /// The payload builder writes the standard's fields where the standard
    /// puts them: most significant bit first at the stated offset.
    #[test]
    fn the_payload_builder_writes_fields_most_significant_bit_first() {
        let bits = Payload::new(24).put(0, 6, 5).put(6, 2, 3).put(8, 8, 0x81).bits();
        assert_eq!(&bits[0..6], &[false, false, false, true, false, true]);
        assert_eq!(&bits[6..8], &[true, true]);
        assert_eq!(&bits[8..16], &[true, false, false, false, false, false, false, true]);
        // ...and text is the payload alphabet, padded with '@'.
        let bits = Payload::new(24).put_text(0, 4, "AB").bits();
        assert_eq!(crate::sixbit::read(&bits, 0, 6), 1);
        assert_eq!(crate::sixbit::read(&bits, 6, 6), 2);
        assert_eq!(crate::sixbit::read(&bits, 12, 6), 0);
    }
}
